apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_f46b7f928fbc5a588f9982a7b4538b99.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_f46b7f928fbc5a588f9982a7b4538b99.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_f46b7f928fbc5a588f9982a7b4538b99.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_f46b7f928fbc5a588f9982a7b4538b99.automount }}
