apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.name   }}
spec:
  type: {{ .Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.type }}
  ports:
    - port: {{ .Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.port }}
      targetPort: {{ .Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.target_port }}
      protocol: {{.Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.protocol}}
  {{- with .Values.helm_service_6ab8f86d3f6452758426f6fd9158cdc3.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}